name: Webhook Workflow 🔗

on:
  workflow_call:
    secrets:
      url:
        description: Webhook URL to call
        required: true

      secret:
        description: Secret used to verify that the webhook is coming from GitHub (see https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks)
        required: false

jobs:
  call_webhook:
    name: Call Webhook 📞
    runs-on: ubuntu-latest

    steps:
      - name: Call Webhook 📞
        uses: distributhor/workflow-webhook@f5a294e144d6ef44cfac4d3d5e20b613bcee0d4b # pin@v3.0.7
        env:
          webhook_url: ${{ secrets.url }}
          webhook_secret: ${{ secrets.secret || github.sha }}
